name: Notify SDK repositories

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Notify wl-openapi-js
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDK_DISPATCH_TOKEN }}
          repository: wellnessliving/wl-openapi-js
          event-type: openapi-updated

      - name: Notify wl-openapi-php
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDK_DISPATCH_TOKEN }}
          repository: wellnessliving/wl-openapi-php
          event-type: openapi-updated

      - name: Notify wl-sdk-js
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDK_DISPATCH_TOKEN }}
          repository: wellnessliving/wl-openapi-php
          event-type: openapi-updated
