name: Notify SDK repositories

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Notify wl-openapi-js
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDK_DISPATCH_TOKEN }}
          repository: wellnessliving/wl-openapi-js
          event-type: openapi-updated

      - name: Notify wl-openapi-php
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SDK_DISPATCH_TOKEN }}
          repository: wellnessliving/wl-openapi-php
          event-type: openapi-updated

      - name: Notify wl-sdk-js (beta)
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: generate-models.yml
          repo: wellnessliving/wl-sdk-js
          ref: beta
          token: ${{ secrets.SDK_DISPATCH_TOKEN }}
